### ISSUE TITLE
Foonathan memory issue while compiling fast-dds for QNX SDP 7.1

### ISSUE THREAD

**Issue by aniketshukla619** [foonathan/memory#125] opened 2021-08-10 04:03 UTC
Hi Everyone,

I'm cross compiling fast-dds for QNX platform. I'm facing foonathan_memory issue. I'm attaching the error and the toolchain file as well for the reference.

[error.docx](https://github.com/foonathan/memory/files/6958889/error.docx)
[fastdds_qnx.zip](https://github.com/foonathan/memory/files/6958890/fastdds_qnx.zip)

Steps followed for building :-

fastdds version - v2.3.3
foonathan_memory version - latest
fastcdr vesrion - latest

git clone https://github.com/eProsima/Fast-DDS.git
cd Fast-DDS
git checkout v2.3.3
mkdir build -p && cd build
source ~/qnx700/qnxsdp-env.sh
cmake .. -DCMAKE_TOOLCHAIN_FILE=qnx_toolchain.cmake -DCOMPILE_EXAMPLES=OFF -DCMAKE_SHARED_LINKER_FLAGS=-lsocket -DCMAKE_CXX_FLAGS=-isystem\ /my/absolute/path/to/folder/containing/__config
make -j3
make install

Same steps were followed for building and compiling Foonathan_memory and Fast-CDR.

Can anyone suggest what mistake I'm doing in which version of foonathan_memory supports this or anyone who has any idea about the issue please help. Thanks.

**Comment by EduPonz** [comment] 2021-08-10 05:23
Duplicate of eProsima/Fast-DDS#2135

**Comment by foonathan** [comment] 2021-08-21 19:15
It seems like you've gotten help in the linked issue.

**Closed** 2021-08-21 19:15 UTC
Labels: duplicate
